version = 0.1
[default.deploy.parameters]
stack_name = "event-harness-test"
resolve_s3 = true
s3_prefix = "event-harness-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
